import type { Exercise } from '@/types';

/**
 * Assessment Exercise Library (Catalyst Version)
 * Based on BrainyAct_Session_Protocols_Claude.docx and BA Catalyst Design sheet
 */
export const ASSESSMENT_EXERCISES: Exercise[] = [
  {
    id: 'face_scan',
    name: 'face_scan',
    displayName: 'Face Scan',
    description: 'Baseline facial recognition and visual attention scan.',
    category: 'visual_tracking',
    phase: 'core',
    durationSeconds: 60,
    unityScene: 'Assessment_FaceScan',
    motionTracking: 'eye',
    levels: [{ level: 1, description: 'Standard scan', successThreshold: 1.0, successStreakRequired: 1 }],
    offlineAvailable: false,
    adaptations: [
      { condition: 'light_sensitive', instruction: 'Reduce screen brightness before starting.' },
    ],
    availableInAssessment: true,
    availableInPlay: false,
  },
  {
    id: 'fukuda',
    name: 'fukuda',
    displayName: 'Fukuda March',
    description: 'Marching in place test to detect vestibular asymmetry and hemispheric bias.',
    category: 'vestibular',
    phase: 'core',
    durationSeconds: 90,
    unityScene: 'Assessment_Fukuda',
    motionTracking: 'full_body',
    levels: [{ level: 1, description: 'March in place for 60 steps', successThreshold: 1.0, successStreakRequired: 1 }],
    offlineAvailable: false,
    adaptations: [
      { condition: 'low_motor_delay', instruction: 'Allow stepping side to side rather than lifting knees fully.' },
    ],
    availableInAssessment: true,
    availableInPlay: false,
    neuroplasticityNote: 'Fukuda rotation > 45° indicates vestibular asymmetry; determines weak hemisphere.',
  },
  {
    id: 'balance',
    name: 'balance',
    displayName: 'Static Balance',
    description: 'Single-leg balance with eyes open and closed to assess vestibular and proprioceptive integration.',
    category: 'vestibular',
    phase: 'core',
    durationSeconds: 240, // ~4 min full; 2 min Catalyst (eyes open only)
    unityScene: 'Assessment_Balance',
    motionTracking: 'full_body',
    levels: [
      { level: 1, description: 'Eyes open, both legs', successThreshold: 0.75, successStreakRequired: 1 },
      { level: 2, description: 'Eyes open, single leg', successThreshold: 0.75, successStreakRequired: 1 },
    ],
    offlineAvailable: false,
    adaptations: [
      { condition: 'low_motor_delay', instruction: 'Allow light fingertip touch on wall for support.' },
    ],
    availableInAssessment: true,
    availableInPlay: true,
  },
  {
    id: 'figure_eights',
    name: 'figure_eights',
    displayName: 'Figure Eights',
    description: 'Tracing figure-8 patterns with arms and legs to assess cross-midline integration.',
    category: 'gross_motor',
    phase: 'core',
    durationSeconds: 300, // 5 min Catalyst
    unityScene: 'Assessment_FigureEights',
    motionTracking: 'full_body',
    levels: [
      { level: 1, description: 'Left arm, 2 rounds', successThreshold: 0.75, successStreakRequired: 1 },
      { level: 2, description: 'Right arm, 2 rounds', successThreshold: 0.75, successStreakRequired: 1 },
      { level: 3, description: 'Left leg, circle trace', successThreshold: 0.75, successStreakRequired: 1 },
      { level: 4, description: 'Right leg, circle trace', successThreshold: 0.75, successStreakRequired: 1 },
    ],
    offlineAvailable: false,
    adaptations: [
      { condition: 'low_motor_delay', instruction: 'Start with a single circle per appendage rather than figure-8.' },
    ],
    availableInAssessment: true,
    availableInPlay: true,
    neuroplasticityNote: 'Cross-midline movement activates corpus callosum and bilateral motor coordination circuits.',
  },
  {
    id: 'cross_crawl',
    name: 'cross_crawl',
    displayName: 'Cross Crawl',
    description: 'Alternating contralateral limb movements to assess bilateral coordination and timing.',
    category: 'gross_motor',
    phase: 'core',
    durationSeconds: 40, // 40 sec Catalyst
    unityScene: 'Assessment_CrossCrawl',
    motionTracking: 'full_body',
    levels: [
      { level: 1, description: 'Standing cross crawl', successThreshold: 0.70, successStreakRequired: 1, windowMs: 180 },
    ],
    offlineAvailable: false,
    adaptations: [
      { condition: 'low_motor_delay', instruction: 'Same-side tap while standing as precursor.' },
    ],
    availableInAssessment: true,
    availableInPlay: true,
    neuroplasticityNote: 'Cross crawl activates contralateral motor cortex pathways and cerebellar timing circuits.',
  },
  {
    id: 'dance_assessment',
    name: 'dance_assessment',
    displayName: 'Dance (Assessment)',
    description: 'Bilateral hand clap sequences to assess auditory-motor timing and bilateral coordination.',
    category: 'gross_motor',
    phase: 'core',
    durationSeconds: 180, // 3 min Catalyst
    unityScene: 'Assessment_Dance',
    motionTracking: 'upper_body',
    levels: [
      { level: 1, description: 'Handclaps only', successThreshold: 0.70, successStreakRequired: 1 },
      { level: 2, description: 'Bilateral movement', successThreshold: 0.70, successStreakRequired: 1 },
    ],
    offlineAvailable: false,
    adaptations: [
      { condition: 'demand_avoidant', instruction: 'Use visual cue (on-screen arrow) instead of verbal instruction.' },
    ],
    availableInAssessment: true,
    availableInPlay: true,
  },
  {
    id: 'bdpq',
    name: 'bdpq',
    displayName: 'BDPQ / Stick Figures',
    description: 'Visual-motor discrimination of mirror-image letters and stick figure orientations.',
    category: 'cognitive',
    phase: 'core',
    durationSeconds: 120, // 2 min Catalyst
    unityScene: 'Assessment_BDPQ',
    motionTracking: 'hand',
    levels: [
      { level: 1, description: '10 BDPQ letters', successThreshold: 0.70, successStreakRequired: 1 },
      { level: 2, description: '10 stick figures', successThreshold: 0.70, successStreakRequired: 1 },
    ],
    offlineAvailable: false,
    adaptations: [],
    availableInAssessment: true,
    availableInPlay: true,
  },
  {
    id: 'piano_hands',
    name: 'piano_hands',
    displayName: 'Piano Hands',
    description: 'Sequential finger tapping patterns to assess fine motor sequencing and bilateral hand differentiation.',
    category: 'fine_motor',
    phase: 'core',
    durationSeconds: 180, // 3 min
    unityScene: 'Assessment_PianoHands',
    motionTracking: 'hand',
    levels: [
      { level: 1, description: 'Single hand sequential tapping', successThreshold: 0.70, successStreakRequired: 1 },
      { level: 2, description: 'Both hands sequential tapping', successThreshold: 0.70, successStreakRequired: 1 },
    ],
    offlineAvailable: false,
    adaptations: [
      { condition: 'low_motor_delay', instruction: 'Wearables/sensor may be needed for accurate hand detection.' },
    ],
    availableInAssessment: true,
    availableInPlay: true,
  },
  {
    id: 'shoot_the_object',
    name: 'shoot_the_object',
    displayName: 'Shoot the Object',
    description: 'Visual-motor targeting exercise to assess eye-hand coordination and reaction time.',
    category: 'visual_tracking',
    phase: 'core',
    durationSeconds: 90, // 1.5 min Catalyst
    unityScene: 'Assessment_ShootObject',
    motionTracking: 'upper_body',
    levels: [
      { level: 1, description: '20 targets', successThreshold: 0.70, successStreakRequired: 1 },
    ],
    offlineAvailable: false,
    adaptations: [],
    availableInAssessment: true,
    availableInPlay: true,
  },
  {
    id: 'digit_span',
    name: 'digit_span',
    displayName: 'Digit Span',
    description: 'Sequential number memory to assess working memory and auditory processing.',
    category: 'cognitive',
    phase: 'core',
    durationSeconds: 120,
    unityScene: 'Assessment_DigitSpan',
    motionTracking: 'none',
    levels: [
      { level: 1, description: '3-digit sequences', successThreshold: 0.70, successStreakRequired: 1 },
      { level: 2, description: '4-digit sequences', successThreshold: 0.70, successStreakRequired: 1 },
    ],
    offlineAvailable: false,
    adaptations: [],
    availableInAssessment: true,
    availableInPlay: true,
  },
];

/**
 * Play Session Exercise Library (Catalyst Version)
 */
export const PLAY_EXERCISES: Exercise[] = [
  {
    id: 'obstacle_challenge',
    name: 'obstacle_challenge',
    displayName: 'Obstacle Challenge',
    description: 'Balance warm-up: static balance for 25 seconds as pre-session activation.',
    category: 'vestibular',
    phase: 'warm_up',
    durationSeconds: 25,
    unityScene: 'Play_ObstacleChallenge',
    motionTracking: 'full_body',
    levels: [
      { level: 1, description: 'Static balance, eyes open', successThreshold: 0.70, successStreakRequired: 1 },
    ],
    offlineAvailable: false,
    adaptations: [],
    availableInAssessment: false,
    availableInPlay: true,
  },
  {
    id: 'hopscotch',
    name: 'hopscotch',
    displayName: 'Hopscotch',
    description: 'Jump to highlighted targets in sequence — timing and proprioception.',
    category: 'gross_motor',
    phase: 'core',
    durationSeconds: 180,
    unityScene: 'Play_Hopscotch',
    motionTracking: 'full_body',
    levels: [
      { level: 1, description: 'Child-paced: advance to next icon after successful jump', successThreshold: 0.60, successStreakRequired: 3 },
      { level: 2, description: 'Timed pace', successThreshold: 0.60, successStreakRequired: 3 },
      { level: 3, description: 'Faster pace', successThreshold: 0.60, successStreakRequired: 3 },
      { level: 4, description: 'Fastest pace', successThreshold: 0.60, successStreakRequired: 3 },
    ],
    offlineAvailable: false,
    adaptations: [],
    availableInAssessment: false,
    availableInPlay: true,
  },
  {
    id: 'moving_sidewalk',
    name: 'moving_sidewalk',
    displayName: 'Moving Sidewalk',
    description: 'Lateral stepping and balance challenge.',
    category: 'gross_motor',
    phase: 'core',
    durationSeconds: 180,
    unityScene: 'Play_MovingSidewalk',
    motionTracking: 'full_body',
    levels: [
      { level: 1, description: 'Slow pace', successThreshold: 0.70, successStreakRequired: 3 },
    ],
    offlineAvailable: false,
    adaptations: [],
    availableInAssessment: false,
    availableInPlay: true,
  },
  {
    id: 'dance_auditory',
    name: 'dance_auditory',
    displayName: 'Dance Auditory',
    description: 'Respond to auditory cues with corresponding body movements.',
    category: 'auditory',
    phase: 'core',
    durationSeconds: 60,
    unityScene: 'Play_DanceAuditory',
    motionTracking: 'upper_body',
    levels: [
      { level: 1, description: 'With visual cue', successThreshold: 0.70, successStreakRequired: 3 },
    ],
    offlineAvailable: false,
    adaptations: [],
    availableInAssessment: false,
    availableInPlay: true,
  },
  {
    id: 'dance_sequence',
    name: 'dance_sequence',
    displayName: 'Dance Sequence',
    description: 'Follow arrow-cued dance sequences to a metronome at 54 BPM (108 BPM music).',
    category: 'gross_motor',
    phase: 'core',
    durationSeconds: 180,
    unityScene: 'Play_DanceSequence',
    motionTracking: 'full_body',
    levels: [
      { level: 1, description: 'Left or right arrow only (based on weak side)', successThreshold: 0.70, successStreakRequired: 3 },
      { level: 2, description: 'Two-direction sequences', successThreshold: 0.70, successStreakRequired: 3 },
      { level: 3, description: 'Full bilateral sequences', successThreshold: 0.70, successStreakRequired: 3 },
      { level: 4, description: 'Complex sequences', successThreshold: 0.70, successStreakRequired: 3 },
      { level: 5, description: 'Advanced bilateral with feet', successThreshold: 0.70, successStreakRequired: 3 },
      { level: 6, description: 'Full pattern', successThreshold: 0.70, successStreakRequired: 3 },
      { level: 7, description: 'Expert', successThreshold: 0.70, successStreakRequired: 3 },
    ],
    offlineAvailable: false,
    adaptations: [],
    availableInAssessment: false,
    availableInPlay: true,
  },
  {
    id: 'cross_crawl_play',
    name: 'cross_crawl_play',
    displayName: 'Cross Crawl to the Beat',
    description: 'Alternating limb cross-crawl timed to a metronome.',
    category: 'gross_motor',
    phase: 'core',
    durationSeconds: 60,
    unityScene: 'Play_CrossCrawl',
    motionTracking: 'full_body',
    levels: [
      { level: 1, description: 'Same-side tap (precursor for red/invalid kids)', successThreshold: 0.70, successStreakRequired: 3, windowMs: 180 },
      { level: 2, description: 'Cross tap', successThreshold: 0.70, successStreakRequired: 3, windowMs: 160 },
      { level: 3, description: 'Cross crawl to beat', successThreshold: 0.70, successStreakRequired: 3, windowMs: 160 },
      { level: 4, description: 'Faster beat', successThreshold: 0.70, successStreakRequired: 3, windowMs: 150 },
      { level: 5, description: 'Expert beat', successThreshold: 0.70, successStreakRequired: 3, windowMs: 150 },
    ],
    offlineAvailable: false,
    adaptations: [],
    availableInAssessment: false,
    availableInPlay: true,
  },
  {
    id: 'figure_eights_play',
    name: 'figure_eights_play',
    displayName: 'Figure Eights',
    description: 'Cross-midline figure-8 tracing with arms and legs.',
    category: 'gross_motor',
    phase: 'core',
    durationSeconds: 180,
    unityScene: 'Play_FigureEights',
    motionTracking: 'full_body',
    levels: [
      { level: 1, description: 'Circle trace, one leg at a time', successThreshold: 0.75, successStreakRequired: 3 },
      { level: 2, description: 'Figure-8 arms', successThreshold: 0.75, successStreakRequired: 3 },
      { level: 3, description: 'Figure-8 legs', successThreshold: 0.75, successStreakRequired: 3 },
    ],
    offlineAvailable: false,
    adaptations: [],
    availableInAssessment: false,
    availableInPlay: true,
    neuroplasticityNote: 'Crossing midline strengthens corpus callosum connectivity.',
  },
  {
    id: 'camera_game',
    name: 'camera_game',
    displayName: 'Camera Game',
    description: 'Full-body movement game using live camera tracking.',
    category: 'gross_motor',
    phase: 'core',
    durationSeconds: 180,
    unityScene: 'Play_CameraGame',
    motionTracking: 'full_body',
    levels: [
      { level: 1, description: 'No timer — child-paced', successThreshold: 0.60, successStreakRequired: 3 },
      { level: 2, description: 'Timed challenges', successThreshold: 0.60, successStreakRequired: 3 },
    ],
    offlineAvailable: false,
    adaptations: [],
    availableInAssessment: false,
    availableInPlay: true,
  },
  {
    id: 'drawing',
    name: 'drawing',
    displayName: 'Drawing',
    description: 'Visual-motor integration through guided drawing paths.',
    category: 'fine_motor',
    phase: 'core',
    durationSeconds: 180,
    unityScene: 'Play_Drawing',
    motionTracking: 'hand',
    levels: Array.from({ length: 8 }, (_, i) => ({
      level: i + 1,
      description: `Drawing level ${i + 1}`,
      successThreshold: 0.70,
      successStreakRequired: 3,
    })),
    offlineAvailable: false,
    adaptations: [],
    availableInAssessment: false,
    availableInPlay: true,
  },
  {
    id: 'digit_span_play',
    name: 'digit_span_play',
    displayName: 'Digit Span',
    description: 'Working memory challenge with sequential number recall.',
    category: 'cognitive',
    phase: 'core',
    durationSeconds: 180,
    unityScene: 'Play_DigitSpan',
    motionTracking: 'none',
    levels: [
      { level: 1, description: '3-digit', successThreshold: 0.70, successStreakRequired: 3 },
      { level: 2, description: '4-digit (adjusted for easier progression)', successThreshold: 0.70, successStreakRequired: 3 },
      { level: 3, description: '5-digit', successThreshold: 0.70, successStreakRequired: 3 },
      { level: 4, description: '6-digit', successThreshold: 0.70, successStreakRequired: 3 },
    ],
    offlineAvailable: false,
    adaptations: [],
    availableInAssessment: false,
    availableInPlay: true,
  },
  {
    id: 'timed_sorting',
    name: 'timed_sorting',
    displayName: 'Timed Sorting',
    description: 'Categorization and processing speed exercise.',
    category: 'cognitive',
    phase: 'core',
    durationSeconds: 180,
    unityScene: 'Play_TimedSorting',
    motionTracking: 'hand',
    levels: Array.from({ length: 4 }, (_, i) => ({
      level: i + 1,
      description: `Sorting level ${i + 1}`,
      successThreshold: 0.70,
      successStreakRequired: 3,
    })),
    offlineAvailable: false,
    adaptations: [],
    availableInAssessment: false,
    availableInPlay: true,
  },
  {
    id: 'twirling_robot',
    name: 'twirling_robot',
    displayName: 'Twirling Robot',
    description: 'Rotational vestibular exercise with controlled spinning.',
    category: 'vestibular',
    phase: 'core',
    durationSeconds: 60,
    unityScene: 'Play_TwirlingRobot',
    motionTracking: 'full_body',
    levels: [
      { level: 1, description: 'Controlled twirl with robot guide', successThreshold: 0.70, successStreakRequired: 1 },
    ],
    offlineAvailable: false,
    adaptations: [],
    availableInAssessment: false,
    availableInPlay: true,
  },
  {
    id: 'dichotic_listening',
    name: 'dichotic_listening',
    displayName: 'Dichotic Listening',
    description: 'Auditory processing exercise with competing sounds to each ear.',
    category: 'auditory',
    phase: 'core',
    durationSeconds: 120,
    unityScene: 'Play_DichoticListening',
    motionTracking: 'none',
    levels: [
      { level: 1, description: 'Simple dichotic task', successThreshold: 0.70, successStreakRequired: 3 },
      { level: 2, description: 'Complex dichotic task', successThreshold: 0.70, successStreakRequired: 3 },
    ],
    offlineAvailable: false,
    adaptations: [],
    availableInAssessment: false,
    availableInPlay: true,
  },
];

export const ALL_EXERCISES: Exercise[] = [...ASSESSMENT_EXERCISES, ...PLAY_EXERCISES];

export const getExerciseById = (id: string): Exercise | undefined =>
  ALL_EXERCISES.find((e) => e.id === id);
